wallpaper {
    monitor = eDP-1
    path = ~/Pictures/wallpapers

    # Elige el ajuste de pantalla (fill o cover)
    fit_mode = fill

    # Tiempo en segundos para cambiar al siguiente fondo (ej. 600 = 10 minutos)
    timeout = 1800
}

splash = false
ipc = on
